### ISSUE TITLE
update whether your external and endogenous factors affected growth or gsl or both

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/grephon#11]
For these columns (all phrased basically like 'Did they look for evidence that external factors, like resources or temperature, limits the length of the growing season (or growing season metric) or limits growth?  Ideally one of these or brief alternative entry'):

**1. authorslooked_externalfactors 
2. authorsfoundevidence_externalfactors
3. authorslooked_endogenousfactors
4. authorsfoundevidencefor_endogenousfactors**

Please update your entries to clarify what they tested (meaning: what specific relationship was the statistic on). Options are ... 

- 	yes - length of growing season
- 	yes - growth
- 	yes - growth and growing season
- 	yes - [insert specific metric of growing season if not length]
-  	yes - [other free form if you cannot use above]
- 	no
- 	not sure* 
- 	NA

Easiest for me is sending me your updated table. Want to download your current table? It's [here](https://github.com/lizzieinvancouver/grephon/tree/main/data/submittedround6).

While you're at it, feel free to specify what type of temperature/precip/moisture matters for external (too high or too low)? Though this is not as critical.

**Comment by lizzieinvancouver** [comment]
As stressed at Monday's meeting, I am still waiting for EVERYONE's updated files. When possible, please cut and paste responses from metadata so I can do less cleaning.

**Comment by lizzieinvancouver** [comment]
@jannekehrl A bunch of your authorslooked_endogenousfactors are still just 'yes' -- can we update to growth versus GSL as you did for authorslooked_externalfactors?

**Comment by lizzieinvancouver** [comment]
@AileneKane Could you work on this while also doing the spp tasks? Thank you!

**Comment by lizzieinvancouver** [comment]
@jannekehrl @AileneKane 

Looks like you entered it well for external but not endogenous ...

```
> unique (d$authorsfoundevidencefor_externalfactors)
 [1] "yes - growth"                                                       "yes - growth anomalies"                                            
 [3] "yes - carbon flux"                                                  "yes - photosynthesis"                                              
 [5] NA                                                                   "yes - length of growing season"                                    
 [7] "yes - growth and growing season"                                    "yes - [gs_end_metric]"                                             
 [9] "yes - growth and growing season (negative gsl growth relationship)" "no"                                                                
[11] "yes - growing season"                                               "not sure"                                                          
> unique (d$authorsfoundevidencefor_endogenousfactors)
[1] NA                       "yes - growth anomalies" "yes - carbon flux"      "yes - photosynthesis"   "no"                     "yes"                   
[7] "yes - [gs_end_metric]"  "yes - growth"
```

And then I check where the yes come from: 

```
> d[which(d$authorsfoundevidencefor_endogenousfactors=="yes"),1:2]
         paper_id who_entered
14      finzi2020    AKE&JHRL
15      finzi2020    AKE&JHRL
18       zani2020    AKE&JHRL
19       zani2020    AKE&JHRL
20       zani2020    AKE&JHRL
21    vitasse2009    AKE&JHRL
23     zohner2020    AKE&JHRL
24 richardson2020    AKE&JHRL
25 richardson2020    AKE&JHRL
26 richardson2020    AKE&JHRL
```

If you edit this, create your own new R file or use tablemergeclean_methodexoendo.R but check with @alanaroseo about that one.

**Comment by AileneKane** [comment]
@lizzieinvancouver and @alanaroseo clarification question: I have corrected this for the "d$authorsfoundevidencefor_endogenousfactors" column in the "clean_AKEJHRL.R" script. Above you also reference the "d$authorslooked_endogenousfactors" column. do you want me to change the looked column as well? If so, should it be exactly the same as the "found" column?

**Comment by AileneKane** [comment]
The code snippets for the "found evidence" cleaning in clean_AKEJHRL.R are:

d$authorsfoundevidencefor_endogenousfactors[d$who_entered=="AKE&JHRL" & d$paper_id=="finzi2020"]<- 
    c("yes - growth [spring NEP] and gs_start_metric relationship differences due to species composition",
      "yes - growth [autumn NEP] and gs_end_metric relationship differences due to species composition")

#select out and clean zani2020 (previously said "yes" only)
d$authorsfoundevidencefor_endogenousfactors[d$who_entered=="AKE&JHRL" & d$paper_id=="zani2020"]<- 
  c("yes - growth and gs_end_metric [greater photosynthesis early in growing season associated with earlier senescence]",
    "yes - growth and gs_end_metric [greater photosynthesis early in growing season associated with earlier senescence]",
    "yes - growth and gs_end_metric [greater photosynthesis early in growing season associated with earlier senescence]")

#select out and clean zani2020 (previously said "yes" only)
d$authorsfoundevidencefor_endogenousfactors[d$who_entered=="AKE&JHRL" & d$paper_id=="zani2020"]<- 
  c("yes - [gs_end_metric]",
    "yes - [gs_end_metric]",
    "yes - [gs_end_metric]")

#select out and clean vitasse2009 (previously said "yes" only)
d$authorsfoundevidencefor_endogenousfactors[d$who_entered=="AKE&JHRL" & d$paper_id=="vitasse2009"]<- 
  c("growth and growing season")
    
#select out and clean zohner2020 (previously said "yes" only)
  d$authorsfoundevidencefor_endogenousfactors[d$who_entered=="AKE&JHRL" & d$paper_id=="zohner2020"]<- 
      c( "yes - growth")
    
#select out and clean richardson2020 (previously said "yes" only)
    d$authorsfoundevidencefor_endogenousfactors[d$who_entered=="AKE&JHRL" & d$paper_id=="richardson2020"]<- 
      c("yes - growth and growing season","yes - growth and growing season","yes - growth and growing season")

**Comment by AileneKane** [comment]
Also, in the clean_AKEJHRL.R script I changed zohner2020 "foundevidencefor_external factors" columnbecuase I believe it was incorrect. @jannekehrl please let me know if you feel i should revert to our previous version or want to discuss this at all
#fixing zohner2020 external factors, which appears to be incorrect (was "yes= length of growing season" but i think it should be "yes= growth") 
    d$authorsfoundevidencefor_externalfactors[d$who_entered=="AKE&JHRL" & d$paper_id=="zohner2020"]<-
    "yes - growth"

**Comment by lizzieinvancouver** [comment]
I think this is done ... @alanaroseo if you don't know of any outstanding issues here, could you please close this?

**Comment by alanaroseo** [comment]
all settled
