### ISSUE TITLE
misc small issues

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/grephon#12]
I need your answers to these queries to update the R code for our table cleaning:

1. @alanaroseo and/or @cchambe12 Can you confirm that in desauvage2022 `ring width` for `growth_metric` is the same as `annual core` ?
2. @FrederikBaumgarten and/or @rdmanzanedo For Oddi2022 last row (wood phenology) how can the `ourdefinition_evidence_gslxgrowth` be 'no data for this' when the entries otherwise suggest to me this is a study that would fit our definition. What am I missing?
3. @jannekehrl and/or @AileneKane Would you be okay with zani2020 and zohnerpreprint being labelled as 'radial growth' method studies?@lizzieinvancouver: I don't think this would be appropriate - both the Zani 2020 and the Zohner preprint (I guess now Zohner 2023) measure photosynthesis on saplings (as well as some other things - each of these studies comes with three lines), so I don't think radial growth really makes sense (since they don't measure this!). Am I missing something?

**Comment by alanaroseo** [comment]
yes, ring width = annual core

**Comment by rdmanzanedo** [comment]
@lizzieinvancouver Regarding 2: I think the issue with that one is that the start of the growing season is not defined (and no info whatsoever on the dendrometers... like at all). No formal testing then with dendrometer data and too confusing to be sure. (Was that your impression too @FrederikBaumgarten ?)

**Comment by lizzieinvancouver** [comment]
> @lizzieinvancouver Regarding 2: I think the issue with that one is that the start of the growing season is not defined (and no info whatsoever on the dendrometers... like at all). No formal testing then with dendrometer data and too confusing to be sure. (Was that your impression too @FrederikBaumgarten ?)

If the start of the season is not defined, then we should not enter `gs_start_metric` as onset wood, perhaps? I am guessing here though.

**Comment by FrederikBaumgarten** [comment]
> @lizzieinvancouver Regarding 2: I think the issue with that one is that the start of the growing season is not defined (and no info whatsoever on the dendrometers... like at all). No formal testing then with dendrometer data and too confusing to be sure. (Was that your impression too @FrederikBaumgarten ?)

yes, totally agree!

**Comment by lizzieinvancouver** [comment]
@rdmanzanedo and @FrederikBaumgarten Okay, can you let me know the plan here? 

@jannekehrl Notes from Monday's meeting were:

> Fredi and Ruben discussed their problem, and suggested and we agreed they should delete the last row (even though dendrometer data mentioned never described / presented), although I suggested they could choose to add a note in bigproblems or whatwewishtheymeasured.

**Comment by lizzieinvancouver** [comment]
@jannekehrl emailed me that "I don't think it would be appropriate to label either Zani or Zohner (unless paper has changed - need to check) as radial growth as they never measure that for any of the six studies, only photosynthesis (leaf level or modeled)" ... 

See below 27 Aug 2023 entry ...

**Comment by lizzieinvancouver** [comment]
@jannekehrl Do you think there is a mis-entry in this line of zohner2023? The entry is 'no' for ourdefinition_evidence_gslxgrowth but they did not measure it, it seems so I think I should update it (in R) to one of the other options (not tested, not tested but have data ... see metadata). 

```
> seemswrong[,c("paper_id", "who_entered", "gsxgrowth", "gsl", "gs_start_metric", "gs_end_metric", "gsxgrowthourdef")] # When this is no rows, we say hurrah!
     paper_id who_entered     gsxgrowth          gsl gs_start_metric
1: zohner2023    AKE&JHRL not mentioned not measured            none
                                                   gs_end_metric gsxgrowthourdef
1: fluxnet derived - last date GPP went below 10% or 25% max GPP              no
```

**Comment by lizzieinvancouver** [comment]
I moved the original 3. above to issue #16

**Comment by lizzieinvancouver** [comment]
@FrederikBaumgarten for camarero2022, can you confirm it would be okay to label it as 'annual core' for growth?

**Comment by lizzieinvancouver** [comment]
- [ ] @jannekehrl @AileneKane I changed the entry I mentioned on 25 July to 'no data for this' which I found listed one column over. Tick this box to confirm you are okay with this.
- [x] @FrederikBaumgarten for camarero2022, if it is okay to label it as 'annual core' for growth when simplifying the column a lot, tick this box
- [x] Check current Oddi2022 situation
- [ ] Deal with some method entries below.

**Comment by lizzieinvancouver** [comment]
Currently two rows of oddi2022 data, with no wood phenology so I think okay.

**Comment by lizzieinvancouver** [comment]
@jannekehrl @AileneKane Currently these rows:

```
   paper_id who_entered                      country                      biome
49 zani2020    AKE&JHRL German, Switzerland, Austria temperate deciduous forest           
zohner2023    AKE&JHRL North America (USA, Canada), Europe temperate deciduous forest
```

are labelled as radial growth for method. If you don't like this labelling, can you pick a better option from here:

```
 unique(d$method)
 [1] "tree ring"             "model"                 "remote"                "eddy covariance"       "synthesis"             ""                     
 [7] "radial growth"         "greenhouse or chamber" "provenance trial"      "height"                "phenology observation"
```

**Comment by AileneKane** [comment]
@lizzieinvancouver @jannekehrl radial growth is not accurate. Both zani2020 and Zohner 2023 should be "greenhouse or chamber", "model" or "synthesis" depending on which component of the studies is included in the focal row (the papers use a combination of experimental, observational, and modeling).

**Comment by lizzieinvancouver** [comment]
@AileneKane Thanks! The columns I showed are uniquely identifying to each row -- so could you let me know what to label each row? If it helps, the zani2020 is 14626 observations and includes 'photosynthesis (total growing-season net daytime photosynthesis, modelled)' as growth  ... I wonder if they are synthesizing PEP725 data and remote sensing and thus we should ask @alanaroseo what category would be best? 

The row in zohner2023 mentions '10 fluxnet sites mostly located in North America and Europe' so I think it should be "eddy covariance" perhaps?

**Comment by lizzieinvancouver** [comment]
Done a while ago.
