### ISSUE TITLE
info on determinate vs indeterminate by species

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/grephon#13]
See [this UBC link](https://quizlet.com/350044463/buds-and-tree-growth-ii-frst-200-ubc-flash-cards/) ... where does this info come from? Who teaches this course? Do they know?

**Comment by lizzieinvancouver** [comment]
@FrederikBaumgarten reported on this Monday and "said the information is harder to find than he thought, but is working on it." @jannekehrl continued "We had a general discussion about how this seems super important (to understanding endogenous factors), might not be as categorical as the two words make it seem, and much less known / studied than we would have expected so bound to come up in the discussion." 

I agree! And I think some of the best info is somewhere in the Forestry group at UBC.

**Comment by rdmanzanedo** [comment]
Anecdotically, image from our green house with the oaks doing 2 very clear growth strechtes (and creating buds in the middle) these are the control ones!
![Imagen de WhatsApp 2023-07-19 a las 12 08 44](https://github.com/lizzieinvancouver/grephon/assets/82371094/ed27cd2f-03a5-42d8-ac22-48bd0d150dfe)
Determinate buds in the first and then able to re-start growth, switch to indeterminate?

**Comment by lizzieinvancouver** [comment]
@rdmanzanedo Cool photo!

@FrederikBaumgarten Can you post your current notes here? And @jannekehrl friendly reminder to ask your molecular colleague about this.

**Comment by lizzieinvancouver** [comment]
Notes I have from Monday are they generally juvenile trees and early-successional are more indet than det. @FrederikBaumgarten See if you can ask Rob Guy and/or Sally Aitken for more info. Also if you can label the species/genera we have in issue #9 -- @AileneKane can add it to plots.

**Comment by FrederikBaumgarten** [comment]
Here some infos I could gather so far:
- Hariharan, I. K., Wake, D. B., & Wake, M. H. (2016). Indeterminate growth: could it represent the ancestral condition?. __Cold Spring Harbor Perspectives in Biology__, __8__(2), a019174.
    **-> Indeterminate growth may be the ancestral form** 
- BORCHERT, R. (1975). Endogenous shoot growth rhythms and indeterminate shoot growth in oak. __Physiologia Plantarum__, __35__(2), 152-157.
    -**> Shoot elongation might seem determinate because of water deficits that resulted from a imbalance of shoot/root ratio. As the shoot elongates root may not be able to supply enough water which results in a hormonal suppression of further shoot growth. This stop and go pattern can result in rhytmic bursts of shoot growth/elongation**
- Marks, P. L. (1975). On the relation between extension growth and successional status of deciduous trees of the northeastern United States. __Bulletin of the Torrey Botanical Club__, 172-177.
    **-> Early successional species adopt a more indeterminate extension growth pattern during a long fraction of the growing season. Species later in the succession in contrast switch towards growing less during a shorter fractino of the GS and show more determinate sxtension growth behaviour.**
- Boojh, R., & Ramakrishnan, P. S. (1982). Growth strategy of trees related to successional status I. 
Architecture and extension growth. __Forest Ecology and Management__, __4__(4), 359-374.
    **-> Same than previous. Additionally they found that early successional species emphazice vertical growth whereas late successional species emphasize broader growth based on their branching architecture probably as a result of competion.**  
**-> Younger trees follow a more indeterminate growth pattern and become more conservative in that regard with age**

**Comment by lizzieinvancouver** [comment]
Thanks @FrederikBaumgarten !

I asked a molecular colleague for some info and she thought there could be links about determinate buds FLC which controls a million things (leaf shape, leaf thickness, cold tolerance, drought tolerance), including vernalization and so controls the switch between what some call `perpetual growth' versus doing it all in one season.

The [Coupland lab](https://www.mpipz.mpg.de/coupland) might have some relevant publications on this 'lifestyle' change. 

Also, this is all epigenetically regulated, so plants shift over time. 

I don't know if there is FLC in trees though ... the only possibly relevant paper I found was [this one](https://nph.onlinelibrary.wiley.com/doi/full/10.1111/nph.17681) on citrus. I think we'd have to dig into the 'competancy' literature to find more, as I am not sure if 'determinate' and 'indetereminate' are used so much anymore (perhaps?).

**Comment by FrederikBaumgarten** [comment]
thanks lizzie for posting even some new terms here! I have talked to Sally and Rob and I am waiting for some more papers that Julie and Tolu are trying to find. I keep you posted!

**Comment by lizzieinvancouver** [comment]
Extremely done. Thanks @FrederikBaumgarten !
