### ISSUE TITLE
need some help on 'classical refs'

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/grephon#18]
We discussed in the fall, but I wanted to revisit this and see if someone wants to tackle this, or better a couple folks as I think we need the historical perspective on:

1. Tree rings
2. physiology
3. Ecology maybe? Not sure, will discuss today.

**Comment by lizzieinvancouver** [comment]
@jannekehrl @AileneKane Any chance either of you could find a graph showing this for elevation or make one from your own data if you cannot find it?

**Comment by lizzieinvancouver** [comment]
@jannekehrl @cchambe12 @FrederikBaumgarten Looking forward to hearing what you find out!

**Comment by cchambe12** [comment]
Sadly, I have extremely limited access to the lit these days but I will contribute articles that look useful from the Abstract. 

1. Huang et al 2010: looks at relationships between temp and precip on radial growth along a boreal latitudinal gradient. Suggests that warming winters and springs will likely result in more growth at more northern latitudes. (https://doi.org/10.1111/j.1365-2486.2009.01990.x)
2. Dario and Neil paper from 2015: Find that precip availability at more northern latitudes was the strongest driver of growth but temperature combined with precip was critical at more southern latitudes (https://onlinelibrary.wiley.com/doi/abs/10.1111/jbi.12462)
3. Gantois 2022: interesting nonlinear trends between temperature and growth, with extreme temperatures having a negative effective on tree growth by 1-5%. In humid climates, temperatures can positively impact growth up to 25-30C but dry climates, temps are best around 10-15C. (https://onlinelibrary.wiley.com/doi/10.1111/gcb.16313).

**Comment by lizzieinvancouver** [comment]
@cchambe12 Thanks! I will try to pull those now and add them to the repo if I can get them.

Also, I just found this:

[Tree growth response along an elevational gradient: climate or genetics?](https://link.springer.com/article/10.1007/s00442-013-2696-6)

> We found that low genetic differentiation among populations indicates gene flow is high, suggesting that migration rate is high enough to counteract the selective pressures of local environmental variation. We observed lower growth rates towards higher elevations and a transition from negative to positive correlations with growing season temperature upward along the elevational transect. With increasing elevation there was also a clear increase in the explained variance of growth due to summer temperatures.

**Comment by lizzieinvancouver** [comment]
@cchambe12 Gantois 2022 was a paper we read last year. The other two I just pushed ... on quick glance I cannot find a paper showing RWI versus elevation or RWI versus GSL ... is there a textbook that might have this @rdmanzanedo ... or other ideas?!

**Comment by AileneKane** [comment]
This seems like a straightforward "ask" that is surprisingly difficult to find good examples of. Most tree ring papers relate growth to climate factors, not elevation. i will look through my grad school files and see what i can find. this paper might be relevant: https://onlinelibrary.wiley.com/doi/abs/10.1111/gcb.15170 here is a figure from it
![image](https://github.com/lizzieinvancouver/grephon/assets/9097640/a500eb94-eefc-4d58-9822-57287c214308)

**Comment by jannekehrl** [comment]
Oops - forgot to add my papers here.

Found a few papers that show (or not) altitude by growth / ring width patterns. Here they are:
- 1998 paper by Oleksyn, on Picea abies (see figure 2)
[oleksyn-1998-dbh-altitude-norway spruce.pdf](https://github.com/lizzieinvancouver/grephon/files/12306343/oleksyn-1998-dbh-altitude-norway.spruce.pdf)

- 2012 paper by Rapp, on these patterns across a tropical elevational gradient (this is a much messier set of relationships, see figures 2 and 3)
[rapp-2012-growth-altitude-tropical.pdf](https://github.com/lizzieinvancouver/grephon/files/12306352/rapp-2012-growth-altitude-tropical.pdf)

- 2007 paper by Coomes, on Nothofagus (graph only shows relationship from model)
[coomes-2007-nothofagus-growth altitude.pdf](https://github.com/lizzieinvancouver/grephon/files/12306370/coomes-2007-nothofagus-growth.altitude.pdf)

- The 2009 Moser paper (we evaluated this for our table) is a nice one looking at growing season length and growth (in European larch) across elevation - no graph with elevation on the x axis (sigh), but figure 4 suggests you would find a negative relationship for both. they took microcores and weekly phenology data.


- However, a 2020 paper by Hikosako did not find convincing altitude by growth, as measured by NPP (see table 2 figure 3)
[hikosaka-2020-altitude growth abies fagus japenese.pdf](https://github.com/lizzieinvancouver/grephon/files/12306469/hikosaka-2020-altitude.growth.abies.fagus.japenese.pdf)


I didn't find any papers looking at this across latitude, although I will say that this doesn't mean these don't exist (there are many many studies in any WOS search, although many not relevant). Here is a good paper (Gillman 2015, see figures 1 and figures 2) illustrating these patterns likely exist (even if not plotted often), showing NPP by latitude patterns in forests (which I would assume inclues annual increment data - but see [here](https://daac.ornl.gov/cgi-bin/dataset_lister.pl?p=13) if we want to check).
[gillman-2015-npp altitude.pdf](https://github.com/lizzieinvancouver/grephon/files/12306454/gillman-2015-npp.altitude.pdf)


Note - most dendro latitude and elevation papers I found focused on how growth sensitivity to climate (e.g. magnitude or identity of climatic variables) varied across latitude and elevation. There are so many papers about this it's hard to find the arguably simpler figures / analyses that document mean growth by altitude / latitude patterns. Here is a good example of that kind of study (Babst 2012 see figure 5)- where it appears the authors could have looked at patterns of growth vs. altitude and / or latitude, but were looking for something different.
[babst-2013-temp vs precip europe.pdf](https://github.com/lizzieinvancouver/grephon/files/12306564/babst-2013-temp.vs.precip.europe.pdf)

**Comment by AileneKane** [comment]
@lizzieinvancouver I think I found 3 papers with some of information we want (all from China) 

1.  In "Altitudinal trends in climate change result in radial growth variation of Pinus yunnanensis at an arid-hot valley of southwest China" by Zhou et al 2022 (https://doi.org/10.1016/j.dendro.2021.125914) they say  "The results showed that the mean width of tree rings decreased as the altitude increasing."  don't have access to the full paper but have requested it and will let you know when i receive it
2. In another paper  (https://www.nature.com/articles/s41598-018-37823-w) they report increasing growth variability (including both mean sensitivity and standard deviation of RWI) at higher altitudes. 
3. This paper (https://doi.org/10.3161/15052249PJE2017.65.4.004) actually made the plot of tree ring width vs elevation (in plot below, sites 1-4 are arranged by increasing elevation) 
<img width="202" alt="image" src="https://github.com/lizzieinvancouver/grephon/assets/9097640/02d1a3f2-1956-4b13-a6d9-595b7998a462">

**Comment by AileneKane** [comment]
Here's paper 1) above, which plotted tree ring width vs elevation: https://doi.org/10.1016/j.dendro.2021.125914
[6262013.pdf](https://github.com/lizzieinvancouver/grephon/files/12326705/6262013.pdf) 
<img width="257" alt="image" src="https://github.com/lizzieinvancouver/grephon/assets/9097640/b42a81a9-e02a-4864-af51-a9e241f06511">

**Comment by FrederikBaumgarten** [comment]
I think this is super relevant for us:
[https://www.sciencedirect.com/science/article/pii/S0168192322000788](url)
<img width="893" alt="image" src="https://github.com/lizzieinvancouver/grephon/assets/116554567/a0890f1b-dc2b-4f15-9503-3434fdb7d902">

**Comment by lizzieinvancouver** [comment]
Okay, between this and emails from Neil Pederson, I am going to try to organize what we have found.

**Comment by lizzieinvancouver** [comment]
> I think this is super relevant for us:
> [https://www.sciencedirect.com/science/article/pii/S0168192322000788](url)

@FrederikBaumgarten Thanks for pointing this out! It is very cool data and seems fairly convincing that within a population earlier individuals do not necessarily grow more ...  From the abstract:

> No clear relationship was found between growing period length and radial growth of oaks within their population.

but not clear they checked between populations.

> However, the detrending process has also the disadvantage of removing the shift in absolute growth rates along the elevational gradient. 

See also section 3.5 of results, which makes this sound confusing (maybe they do find it but it depends on elevation?).

**Comment by AileneKane** [comment]
@lizzieinvancouver I updated our [tree growth vs elevation figures.](https://github.com/lizzieinvancouver/grephon/blob/main/analyses/growthxelevationetc/figures/grbyelevbig.pdf) Some questions/additional things we could do to improve them, if desired:

1. Instead of Elevation, use a metric of growing season length (e.g., snow free days, GDD). Do you want me to do this for the MORA data? (not sure we can for the other)
2. If we do this, we could incorporate each year of growth and growing season length (Currently "Growth" averaged across most recent 20 years)
3. Note for the top panel growth = ring width and for the bottom panel growth = basal area index. I have also made [a plot comparing ring width to basal area index ](https://github.com/lizzieinvancouver/grephon/blob/main/analyses/growthxelevationetc/figures/grbyelev_rwvsbai_big.pdf)(the elevational patterns differ). Do we want to discuss this- perhaps in the growth box? or just stick to one growth metric for mora- perhaps bai- and leave out the discussion. 
4. What else should I change about these figures?

**Comment by lizzieinvancouver** [comment]
@AileneKane Thanks for this! I like the new figures. Some quick replies ...

1. I really like this idea as I am not sure anyone has done it! And it seems a very good test ... that said, we could wait to discuss if we would use it in the paper. I think we would but depends on other figures and which way the text goes.
2. I like this idea a lot -- it could potentially be a separate figure to show where we want dendro to go perhaps? You know dendro better than me though so would be able to think through that more than I can.
3. I like the point, but let's see how long the paper is first, perhaps? I am hoping not too focus so much on metrics personally ... but not sure ... and could be interesting perhaps for @rdmanzanedo paper?
4. Nothing yet beyond maybe trying (2) to me, I think we can discuss better once I embed them in a new draft ... which I am working on now. 

Thank you again!

**Comment by lizzieinvancouver** [comment]
Note to self: If we use this, we should work on a table to organize these refs -- maybe a list of all we checked (see what Britany did; incl. Neil's emails)

**Comment by lizzieinvancouver** [comment]
This is done, connects to issue #24
