### ISSUE TITLE
Important statements you think the paper should include

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/grephon#19]
Post statements/snippets you think we need to include in paper.

**Comment by alanaroseo** [comment]
Where my physiologists at? We are mostly measuring this growth/phenology stuff without digging deep into mechanisms, we need more interdisciplinary work/cross talk to figure out what is going on when we either do or don't find a link between growing season and growth. Carbohydrate and cell division/expansion dynamics are especially promising.

**Comment by cchambe12** [comment]
Agreed with Alana! We're finding consistency with relationships between phenology and temperature but maybe growth is dependent on other environmental elements (VPD, precipitation, etc.) and therefore phenology isn't the best proxy for growth without understanding the mechanisms. 

Also! We need to think about key disturbances throughout the growing season. Yes, maybe the season starts earlier and ends later, but what's happening in the middle? Are there droughts, false springs, intense heat waves? All of which would impact growth. 

Our definition of phenology could also be playing a role. I'm especially thinking about EOS. I feel like budset might be a better predictor of growth than say leaf senescence.

**Comment by lizzieinvancouver** [comment]
@rdmanzanedo at today's meeting mentioned a good point: We have tested this across MANY species and (from @AileneKane figures) are seeing inconsistent findings.

**Comment by rdmanzanedo** [comment]
@lizzieinvancouver yeah, my comment was more in the direction that this lack of consistency is not linked to a particular species or country, but found across all of them, so its not a matter of the study system but a deeper problem of the field. Not sure if that is what you meant.

**Comment by rdmanzanedo** [comment]
ohter statements:

**Crosstalking and unifying**: there are way too many related but not synonymous concepts and metrics that are used inconsistently and are likely preventing seeing a more consistent picture. This happens between fields but also within ones (e.g. metrics of GSL). This compounds with the fact that clearly reporting which metrics are used and how they may affect outcomes is not common.  Ideally, we may point at opening the discussion towards developing standard metrics , similarly to the push towards standardizing ecosystem services that is going on now. 

**Missing chances**: it would be great to gather some of the ideas of easy paths of advance we see (and that we have discussed quite a bit last months), for example, better and more formal implementation of tree ring analyses to answer the question. Pointing at some of this 'low hanging fruit' options would be great, if we can think of them and are sure we understand why they are (or aren't) being implemented.

**Comment by jannekehrl** [comment]
Important things that have struck me and I believe are important:
- Lack of standard ways to tackle this question (even when putatively addressing the same question), even when using the same type of data. This is something this paper can hopefully help - what are the important explanatory variables, response variables, do we have opinions on how they should be measured, etc? Ditto for statistical approaches. Of course, there are some real differences in approaches and methods depending on what data you have - but it really hampers cross study comparison when everyone is doing their own thing.
- Lack of mechanistic understanding for when and why growth should increase with GSL and when or why it should not. This is similar to Alana's puzzlement about the lack of physiological understanding of these patterns, but I suspect also extends to the sense that developmental / genetic constraints can occur. I think this is particularly important if we are going to use these relationships and any constraints we find to project - extrapolating is particularly dangerous when you have the underlying models wrong.
- Low hanging fruit would also be good to point out.

**Comment by lizzieinvancouver** [comment]
I think we have covered what we could and any lingering things here I leave to boil up through replies to new draft.
