### ISSUE TITLE
Simplify exogenous (table)

### ISSUE THREAD

**Issue by rdmanzanedo** [lizzieinvancouver/grephon#21]
Proposed table to simplify exogenous variables from what we have to a common set:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/rdman/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/rdman/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Exo.var | Temp | Prec | CO2 | Day.Length | Elevation | Soil.moisture.water.content | Land.cover | Tree.density | Shade | Nitrogen | Disturbances | VPD | latitude
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
autumn temperature, winter chilling,   spring temperature | 1 |   |   |   |   |   |   |   |   |   |   |   |  
CO2, warming and their interaction | 1 |   | 1 |   |   |   |   |   |   |   |   |   |  
day length |   |   |   | 1 |   |   |   |   |   |   |   |   |  
elevation |   |   |   |   | 1 |   |   |   |   |   |   |   |  
high summer temperatures | 1 |   |   |   |   |   |   |   |   |   |   |   |  
reduced soil moisture |   |   |   |   |   | 1 |   |   |   |   |   |   |  
Seasonal precip and May temp | 1 | 1 |   |   |   |   |   |   |   |   |   |   |  
spring temperature mainly, but also   elevation, precipication (they also looked at land cover and other climate   variables) | 1 | 1 |   |   | 1 |   | 1 |   |   |   |   |   |  
stand density and thinning method |   |   |   |   |   |   |   | 1 |   |   |   |   |  
sun vs. shade |   |   |   |   |   |   |   |   | 1 |   |   |   |  
temp | 1 |   |   |   |   |   |   |   |   |   |   |   |  
temperature (pre solstice) | 1 |   |   |   |   |   |   |   |   |   |   |   |  
temperature (pre solstice) , shade/light,   nutrients, drought | 1 | 1 |   |   |   |   |   |   | 1 | 1 |   |   |  
temperature (summer, autumn), CO2 | 1 |   | 1 |   |   |   |   |   |   |   |   |   |  
temperature and soil water content | 1 |   |   |   |   | 1 |   |   |   |   |   |   |  
temperature at SOS | 1 |   |   |   |   |   |   |   |   |   |   |   |  
temperature, CO2, N, disturbance | 1 |   | 1 |   |   |   |   |   |   | 1 | 1 |   |  
temperature, GDD | 1 |   |   |   |   |   |   |   |   |   |   |   |  
timing of rainfall impacts growth not gsl |   | 1 |   |   |   |   |   |   |   |   |   |   |  
mean GDD and mean growing-season   precipitation | 1 | 1 |   |   |   |   |   |   |   |   |   |   |  
site difference |   |   |   |   |   |   |   |   |   |   |   |   |  
soil water content |   |   |   |   |   | 1 |   |   |   |   |   |   |  
temperature | 1 |   |   |   |   |   |   |   |   |   |   |   |  
VPD, SWP, Temp, Precip | 1 | 1 |   |   |   |   |   |   |   |   |   | 1 |  
latitude |   |   |   |   |   |   |   |   |   |   |   |   | 1
spring temperature | 1 |   |   |   |   |   |   |   |   |   |   |   |  

</body>

</html>

Most of this categories are represented by a single entry. If anyone identifies a problem with the assignment of what they wrote, should be easy to guess which one is yours and please let me know.

@alanaroseo @lizzieinvancouver is this compatible with what you guys where doing on simplifying the factors manually? I think it provides different information and we can easily do a more informative barplot of how many take into account different angles. thoughts?

**Comment by rdmanzanedo** [comment]
(table was incorrectly imported, has been corrected)

**Comment by alanaroseo** [comment]
@rdmanzanedo I think this would be a nice way to make a figure. Maybe would should simplify further, like lumping soil moisture and precip into "water availability" and combining some things with only one representative study? like maybe land cover and tree density? 
This is also similar to presence only data in that we don't have notes on what they looked at but didn't find, only what they found @lizzieinvancouver any ideas on interpreting that?

**Comment by lizzieinvancouver** [comment]
@rdmanzanedo Seems good to me! I agree we'll likely want this version and some code to way simplify it down. I have actually been working on a list to organize the possible hypotheses for GSL not relating to growth so maybe we can connect to that once we have it ...

@alanaroseo For our purpose here, I think it would be bad if there is an entire hypothesis that is ONLY tested and never found. I suspect this table covers a mix of things tested and not found in other studies. ... so seems okay for our purposes (vague and general overview), but **we should discuss on Wednesday** if anything big seems missing that was tested.

**Comment by lizzieinvancouver** [comment]
Discussion today no one mentioned a big thing missing because it was not fond to matter (and so not added to table) ... @jannekehrl felt like she did not see biotic interactions, but maybe she would have ignored it (because she think biotic would  add noise).

**Comment by rdmanzanedo** [comment]
Updated according to @alanaroseo comment. Not sure it's better than what she coded manually reducing it even further, but maybe for the barplot?

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/rdman/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/rdman/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Exo.var | Temp | Prec&moisture | CO2 | Day.Length | Elevation | Stand.characteristics | Shade | Nitrogen | Disturbances | VPD | latitude
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
autumn temperature, winter chilling,   spring temperature | 1 |   |   |   |   |   |   |   |   |   |  
CO2, warming and their interaction | 1 |   | 1 |   |   |   |   |   |   |   |  
day length |   |   |   | 1 |   |   |   |   |   |   |  
elevation |   |   |   |   | 1 |   |   |   |   |   |  
high summer temperatures | 1 |   |   |   |   |   |   |   |   |   |  
reduced soil moisture |   | 1 |   |   |   |   |   |   |   |   |  
Seasonal precip and May temp | 1 | 1 |   |   |   |   |   |   |   |   |  
spring temperature mainly, but also   elevation, precipication (they also looked at land cover and other climate   variables) | 1 | 1 |   |   | 1 | 1 |   |   |   |   |  
stand density and thinning method |   |   |   |   |   | 1 |   |   |   |   |  
sun vs. shade |   |   |   |   |   |   | 1 |   |   |   |  
temp | 1 |   |   |   |   |   |   |   |   |   |  
temperature (pre solstice) | 1 |   |   |   |   |   |   |   |   |   |  
temperature (pre solstice) , shade/light,   nutrients, drought | 1 | 1 |   |   |   |   | 1 | 1 |   |   |  
temperature (summer, autumn), CO2 | 1 |   | 1 |   |   |   |   |   |   |   |  
temperature and soil water content | 1 | 1 |   |   |   |   |   |   |   |   |  
temperature at SOS | 1 |   |   |   |   |   |   |   |   |   |  
temperature, CO2, N, disturbance | 1 |   | 1 |   |   |   |   | 1 | 1 |   |  
temperature, GDD | 1 |   |   |   |   |   |   |   |   |   |  
timing of rainfall impacts growth not gsl |   | 1 |   |   |   |   |   |   |   |   |  
mean GDD and mean growing-season   precipitation | 1 | 1 |   |   |   |   |   |   |   |   |  
site difference |   |   |   |   |   |   |   |   |   |   |  
soil water content |   | 1 |   |   |   |   |   |   |   |   |  
temperature | 1 |   |   |   |   |   |   |   |   |   |  
VPD, SWP, Temp, Precip | 1 | 1 |   |   |   |   |   |   |   | 1 |  
latitude |   |   |   |   |   |   |   |   |   |   | 1
spring temperature | 1 |   |   |   |   |   |   |   |   |   |  



</body>

</html>

**Comment by rdmanzanedo** [comment]
![barplotexo](https://github.com/lizzieinvancouver/grephon/assets/82371094/700ffd09-d371-45c8-b178-034466a46e8f)

**Comment by lizzieinvancouver** [comment]
@rdmanzanedo This seems good for now! I am reviewing all the code the next couple of days, and will ping if I have better ideas. Can you post the file to the github or email to me so we have it?

**Comment by lizzieinvancouver** [comment]
I believe this is done!
