### ISSUE TITLE
what is the most critical next step?

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/grephon#23]
Would love to hear any thoughts/ideas on:

- What is the most critical experiment or observational dataset we need for understanding GSL x growth relationships?
- What is the most critical open question we need answered for understanding GSL x growth relationships?
- Any variant of the above.

**Comment by AileneKane** [comment]
Observational/low hanging fruit: analyze ring width or some growth metric across elevational gradient and quantify growing season length along that elevational gradient to quantify the extent to which growing season length affects growth. This is is obviously not sufficient to project effects of increased growing season length (from climate change) on growth but it should give some sense of how much growing season length affects growth, along a gradient where other factors also vary (e.g. stand age, competition, resources not related to gsl)

**Comment by jannekehrl** [comment]
Agreed with @AileneKane - there is a lot to be done with the vast existing tree ring databases, across both latitude and elevation, to better understand the relationship within and between species, over time, etc. 

I also think there are low hanging fruit with provenance studies - e.g. coring them, measuring phenology on them, etc.

I don't know if this is low hanging fruit, but collaborating with physiologists and plant developmental biologists on experiments perhaps in model systems, could also be really interesting - that could help get at some of the drivers of endogenous limits I am really fuzzy on (and I think the field is as well).

**Comment by FrederikBaumgarten** [comment]
Experiments testing the effect of GS expansion (at both sides) on growth increments over 2 GS (because autumn warming might increase growth only in the next year if at al). This should be done under favourable conditions (e.g. fully watered conditions) as we already know that drought will stop growth processes.

**Comment by kavs-P** [comment]
Not sure if these are critical questions/critical experiments, but here are some thoughts:

- latitude or altitude vs growth. Would be cool to actually demonstrate this

- The amount of growth that is happening at each point in the growing season and how is it related to GSL. The question I have here is if earlier GS means that peak growth will happen early, then if maybe poor conditions later in the GS don’t matter as much, or maybe they do? Or if there are endogenous constraints on the peaking of growth then shifts to earlier GS wouldn’t really help at all

- We’ve talked about this before but collecting cores from places where phenology has been already recorded and is continuing to be recorded would be really important for examining long term changes and trends. It seems to me like collecting cores would be more feasible than collecting phenology data (which you’d need to visit every location multiple times)

- Also still really curious about where the carbon goes. How much of it goes to growth vs maintenance or reproduction or whatever else. Would be cool to track it in flux tower areas where they can detect the CO2 drawdown across the season showing that photosynthesis is happening earlier but if we’re not detecting radial growth then what is the consequence of this earlier photosynthesis start. Another way to look at this could be an experiment where we would tag CO2 (can you tag CO2? maybe isotopes) and then destructively sample the plants at different points along the growing season to find out where the CO2 went? Of course the caveat being that it would likely be juveniles, or model organisms so how much would we really be able to extrapolate?

**Comment by cchambe12** [comment]
I'm not sure the best way to test this but I think competition would be an interesting next step to explore. I feel like every forester has a story about a 40 year old oak that's 5 feet tall. I'd be especially interested in seeing how water availability interacts with competition. I'm not sure how feasible this would be but maybe a common garden experiment with a competition x drought gradient.

**Comment by lizzieinvancouver** [comment]
This wrapped up a while ago so closing now!
