### ISSUE TITLE
GREPHON table heatmap etc.

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/grephon#28]
See also issue #25: Figure of the results from GREPHON team? Maybe Cat and Rubén and Alana could work on this? Heatmap of results based on growth measurements types x GSL types @cchambe12 will work on this.

I should be back in 10 or so days and maybe we can meet then to discuss? ... until then the README in analyses will all make sense to you... and I am pasting in just some of the bits I thought we could support with the lit review results (though I am SURE that I have missed some):

> A systematic review of the literature highlights a focus on external climatic drivers limiting growth in annual tree ring studies, while lab experimental and woody phenology (xylogenesis studies) focus on physiological constraints (spanning 37 papers and 60 unique tests or studies; see Supp or Fig/Table). Further, we found little support for reports of a disconnect between growth and growing season length. Instead the field has generally found split support---across methods---for the when longer seasons lead to increased growth, suggesting that understanding the relationship mechanistically will be critical to accurate predictions. 
> 
> **External/internal drivers ...**
> 
> A suite of mechanisms, both external---including climatic and biotic drivers---and internal can alter any simple growth x season length relationships. But a tendency to focus on only one or the other means we have little understanding of how they compare, or which may explain current findings. 
> 
> Research into external abiotic drivers is the bread and butter of dendrochronologists and they cannot stop themselves from running a gazillion tests of how ring width correlates with easy-to-get climate variables: temperature and precipitation. 
> 
> Almost unmentioned in dendrochronology, internal constraints on plant growth are the bouncy castle of plant physiology
> 
> Mechanistic physiology studies rarely measure (or even include) competition and, given dendrochronology's focus on climatic signal through growth, the field similarly tries to avoid the study or impact of plant competition, even though it is foundational to forest dynamics.

**Comment by cchambe12** [comment]
@lizzieinvancouver I built a couple of heatmaps for us to start with. I can certainly modify as we see fit! One thing to note, for the 'gsl' and 'gslsimple' columns, there were entries for both 'not measured' and 'NA'. I merged these to all be considered 'not measured' but please let me know if that is correct. 

You can find the heatmap for the complete list here: https://github.com/lizzieinvancouver/grephon/blob/main/figures/heatmap_gslxgrowth_complete.pdf

And the heatmap for the simple versions here:
https://github.com/lizzieinvancouver/grephon/blob/main/figures/heatmap_gslxgrowth_simple.pdf

**Comment by lizzieinvancouver** [comment]
@cchambe12 These are so cool! Thanks for doing them, and thinking of them. Great idea.

Do the counts show often they were tested or how often they found a 'yes' or 'no' for the relationship ?

**Comment by cchambe12** [comment]
@lizzieinvancouver it’s showing how often they were tested but that’s a cool idea to do “no” and/or “yes”! I’ll work on those over the next couple of days

**Comment by lizzieinvancouver** [comment]
@cchambe12 Awesome -- that would be great. Thanks again!

**Comment by cchambe12** [comment]
@lizzieinvancouver I'm working on revamping the heatmaps a bit and am realizing there are a few instances where 'gslsimple' is labelled as "not measured" and we entered "yes" for the 'youthink_evidence_gsxgrowth'. This seems wrong to me. Should I change these all to "No" instead or am I misremembering something?

**Comment by cchambe12** [comment]
> @lizzieinvancouver I'm working on revamping the heatmaps a bit and am realizing there are a few instances where 'gslsimple' is labelled as "not measured" and we entered "yes" for the 'youthink_evidence_gsxgrowth'. This seems wrong to me. Should I change these all to "No" instead or am I misremembering something?

Never mind! I've switched to using the "ourdefinition_evidence_gslxgrowth" which has been cleaned more recently.

**Comment by cchambe12** [comment]
@lizzieinvancouver I've made a new heatmap combining all the simple pieces together, what do we think of this? 
https://github.com/lizzieinvancouver/grephon/blob/main/figures/heatmaps/combinedheatmap_gslxgrowth_simple.pdf

**Comment by lizzieinvancouver** [comment]
@cchambe12 Ooh, I love it! Perhaps we should keep this version for the supp, and make one where we drop 'negative relationship' (right panel) and 'root:shoot' (top row) for the main text?

Also, I was wondering if we could also use the heat maps to visualize what types of studies (`method` column ... hmmm and/or `growthsimple`) look at what exogenous/endogenous effects (`what.endo` and `what.ext `columns)?

**Comment by lizzieinvancouver** [comment]
@cchambe12 Not pretty, but totally do the job for now ... I posted some of the endo/exo heat maps in commit 27925f865d1e24761f353e26e91fb5cbc843520c

**Comment by lizzieinvancouver** [comment]
@cchambe12 Would be great if you can fix the ugly heat maps and figure out 1-2 that are really useful for statements like:

> if tackled with a more organized interdisciplinary approach. Most fields studying growth × growing season length relationships consider a limited set of metrics and a small subset of possible drivers (see Figs. 3, S1). Beyond failing to test a suite of highly relevant mechanisms, the lack of interdisciplinary study means we lack coherent tests that compare multiple mechanisms.

**Comment by cchambe12** [comment]
@lizzieinvancouver I updated the supp heatmaps and added the new file to the Supp Rnw but I did not compile because sometimes it does wonky things across computers! I will close for now but please feel free to reopen if you want me to further tweak to figures!
