### ISSUE TITLE
measurement box text

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/grephon#30]
see also issue #25 ....

**Comment by lizzieinvancouver** [comment]
@AileneKane Added this, I just tweaked it some with commit 70398d43bbc8ba8fcb9b7386cff0dc2616b1392a ... I'll close it once I add a reference to it in main text, mentioning that Korner paper covers phenology so we don't.

@AileneKane Could you recommend some refs for "e.g. from LPJ, InTEC, or other models, REFS"? You can either add to GREPHON bib or paste bibtex versions of them here in the issue and I will add. Thank you!

**Comment by AileneKane** [comment]
I have added a reference to Smith et al (cited by zohner2023) in the Rnw file. here is the bibtex:
@article{smith2014implications,
  title={Implications of incorporating N cycling and N limitations on primary production in an individual-based dynamic vegetation model},
  author={Smith, Benjamin and W{\aa}rlind, David and Arneth, Almut and Hickler, Thomas and Leadley, Paul and Siltberg, Joe and Zaehle, S{\"o}nke},
  journal={Biogeosciences},
  volume={11},
  number={7},
  pages={2027--2054},
  year={2014},
  publisher={Copernicus GmbH}
}

**Comment by AileneKane** [comment]
I also added a reference for chen et al 2000"Approaches" (cited by chen et al 2000!). Here's the bibtex for that:
@article{chen2000approaches,
  title={Approaches for reducing uncertainties in regional forest carbon balance},
  author={Chen, Wenjun and Chen, Jing and Liu, Jane and Cihlar, Josef},
  journal={Global Biogeochemical Cycles},
  volume={14},
  number={3},
  pages={827--838},
  year={2000},
  publisher={Wiley Online Library}
}

**Comment by lizzieinvancouver** [comment]
@AileneKane Thanks, I added this.

**Comment by lizzieinvancouver** [comment]
@AileneKane I think this is all set -- thank you!
