### ISSUE TITLE
stuff to make sure we back up with the table ...

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/grephon#35]
**Definitely:**

1. Further, the consistency of varying results, with no clear pattern by method or even within species---suggests that understanding the relationship mechanistically---will be critical to accurate predictions. Maybe update the figure on species for this?

**Maybe:** 

1. We found most physiological studies of growth $\times$ growing season length relationships studied 1-2 years of dynamics, usually of juvenile trees, while tree ring studies are focused on synthesizing across decades or longer of adult tree growth

**Comment by lizzieinvancouver** [comment]
@cchambe12 Please do quick skim for anything we should back (or anything you think we can add) ....

We agreed for stuff like the below, we will publish data and code (and skip a giant messy table unless really asked for by reviewers): 

> We found 14 different metrics of start and 16 metrics of end of season (25 metrics of growing season length), and 21 different metrics of growth across 59 studies—highlighting just part of the problem. Definitions and metrics for external and internal drivers were myriad, with many papers reporting dozens of tests of different aspects of climate over different temporal windows.

Think on a minimal reference table we should add (ref, and 1-2 columns we have) to supp.

**Comment by cchambe12** [comment]
@lizzieinvancouver I added a really quick reference list table with country and biome, happy to keep iterating if we think it could actually be useful. See figures/referencetable.pdf

**Comment by cchambe12** [comment]
@lizzieinvancouver The MS looks great!! I've gone through and added some small edits and comments where we could consider adding in references to our lit review data. Maybe we can set up a call again in the new year to go through those comments and whether or not we want to add in more numbers in those places. I'd be happy to add them via \Sexpr{} after we settle on what seems valuable.

**Comment by lizzieinvancouver** [comment]
@cchambe12 Thank you for this!!! Yes, let's set up a time to talk as I want to move on GREPHON and get a new draft out ... aiming for late January/early Feb ... after I get through a Bayesian week I am running at UBC. If you can, email me some times you have the week of Jan 29.

**Comment by lizzieinvancouver** [comment]
I think this is all set!
