### ISSUE TITLE
Source vs Sink

### ISSUE THREAD

**Issue by alanaroseo** [lizzieinvancouver/grephon#37]
OMG, this topic is a mess!!!!!

Here's a definition attempt and some text:

In the context of forests, a **_source limitation_** refers to factors that hinder the capacity of a forest system to absorb carbon dioxide from the atmosphere while a **_sink limitation_** refers to factors that constrain or reduce the capacity of a forest to retain and store carbon over time. Thus external climatic factors AND endogenous factors such as species identity play a role in both source and sink limitations and their interaction with tree growth. While these are common terms is both physiology and carbon-stock assessment, they are not consistently defined and therefor are difficult to mesh with our focus on the tree growth x growing season length relationship.

**Comment by lizzieinvancouver** [comment]
@alanaroseo Thank you! Do you want to add any refs? (If yes, and you want to paste them as bibtex code I would appreciate it, but not critical).

**Comment by lizzieinvancouver** [comment]
Added to caption for Fig. 1.
