### ISSUE TITLE
make figures more consistent and generally better... 

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/grephon#40]
Per talking with @rdmanzanedo I will upload SVG images of Fig on elevation (to do! waiting on help for issue #24 from @buniwuuu) and fig on temperature curves (done, see figures/tempresponse folder). 

Temperature curve figure is based on this figure from Larcher with NO units:

![Graph](https://github.com/lizzieinvancouver/grephon/assets/2153556/b24fbb75-4e5c-41e4-aa72-3de0d8efb4d3)

And this one that I generalized to one curve, which has units (from Rezende & Bozinovic 2019):

![Screen Shot 2024-05-22 at 11 33 36 AM](https://github.com/lizzieinvancouver/grephon/assets/2153556/2b4c5070-d50b-4ffa-befe-117b62ed74b0)

And figure 1 needs to be updated with new numbers and maybe new names to some hypotheses. The current short-hand names I have are:

- effect of growth rate not equal to growth duration: 6
- Higher temp = more growth (temp limitation): 9 -- this falls under earlier-longer-more growth
- internal constraints (including pop, photo): 6
- Longer growing season = more growth: 10 (and these relate to more time more growth)
- More temp = more drought (drought limitation): 8
- shift in allocation: 1
- shift of whole pheno sequence: 6 (longer growing season != more growth)
- species-specific responses: 3

**Comment by lizzieinvancouver** [comment]
@rdmanzanedo Thanks for your offer of help to beautify the main text figures!

Here's the current locations of all figures for the manuscript in the repo:

1. figures/hypothesesconceptfig.png (your figure)
2. analyses/growthxelevationetc/figures/growthbyelevation_plot.pdf (made in R) 
3. figures/heatmaps/combinedheatmap_gslxgrowth_simple.pdf (must be made in R ... but could check with @cchambe12 for code and to confirm)
4. figures/tempresponse/drafttempfig.png (needs help! I also uploaded a SVG)
5. figures/itrdbpep.png (your figure)

I think they are all ready for any tweaks you think they need. For (1) and probably (3), there is R code we could likely edit directly so if you have a color pallette you suggest that me and @cchambe12 use, then we can! I will email you the colorchart in case it helps. 

For any figures you edit in another format, can you upload the edit-able file (.ai or .svg) also so I have it alongside the one to use in the manuscript (PDF and/or PNG for now works).

And if you need help with git or just want to send via email, that's fine! Let me know.

**Comment by lizzieinvancouver** [comment]
@cchambe12 I am using this issue to keep track of the supp heatmap ... The new supp heatmaps look good to me, but now I am working on the caption and want to confirm with you. Right now we have:

> A review of the prevalence of external (left) and internal (right) drivers mentioned in studies from our literature review, grouped by the method used to measure growth, which shows differences across fields, study types, and metrics. Many studies tested related hypotheses by measuring different drivers (e.g., latitude or elevation), thus so we combined similar external and internal factors for clearer comparisons.

Does that work? Can you confirm the `method` relates to growth? I think I am wrong as phenology observation is not one of the methods for growth.

**Comment by cchambe12** [comment]
@lizzieinvancouver Nice catch! Yeah I think you're right. We're more outlining the different study types by external and internal factors. This figure has been confusing me a bit after a bit of time. I'm not sure what to make of "Height" being included on the vertical axis for method alongside other study types like "Greenhouse or chamber" or "Synthesis". 

One question: should I change the "Height" term to something more consistent with the other Method terms? I feel like "Height" in this case should be classified as "Field" or "Greenhouse or chamber" or even "Remote". 

And, if so, then maybe we can tweak the caption a bit to this: A review of the prevalence of external (left) and internal (right) drivers mentioned in studies from our literature review, grouped by the method used to test hypotheses, which shows differences across fields, study types, and metrics. Many studies tested related hypotheses by measuring different drivers (e.g., latitude or elevation), thus so we combined similar external and internal factors for clearer comparisons.

**Comment by lizzieinvancouver** [comment]
@cchambe12 Thank you for working with me on this! I went back and cleaned up our basic code, including finding an error. I think the updated heat map categories make more sense (see what you think) and suggest we simplify the caption to:

> A review of the prevalence of external (left) and internal (right) drivers mentioned in studies from our literature review, grouped by the general methods used. Many studies tested related hypotheses by measuring different drivers (e.g., latitude or elevation), so we combined similar external and internal factors for clearer comparisons

If you have time -- before we finalize the figure, I'd appreciate another set of eyes on analyses/source/clean_methodexoendo.R which is where I made the edits. It runs from cleantableall.R

**Comment by lizzieinvancouver** [comment]
@cchambe12 I just submitted, but am leaving this open as one more set of eyes on the code would be good if you can do that in the next few weeks. Thank you again for all your work on this!

**Comment by cchambe12** [comment]
@lizzieinvancouver Sorry I was MIA for the end there! But I just reviewed the code and I think it looks great now. I did several checks and was unable to find any errors and I think it looks much improved. Thanks!

**Comment by lizzieinvancouver** [comment]
@cchambe12 Great! I think we're all set and I will close this issue now. Thanks for all your help on this.
