### ISSUE TITLE
finalize supp heatmap

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/grephon#41]
@cchambe12 Can you make sure the heatmap: heatmap_combined_endo&exo.pdf that I plan to use in the supp is in good order and try to match main text background colors if important? If you can also help with a better caption, I would appreciate it!

See also git issue #28

**Comment by cchambe12** [comment]
@lizzieinvancouver I tried to update the appearance a bit to match the main text heatmap. I think they look a bit different after Ruben cleaned up the main figures and made them look pretty! But I did my best to match the new colors. I also updated the caption with more information
