### ISSUE TITLE
review early issues with double entry

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/grephon#6]
Hurdle 1 is people not submitting everything, but I assume we can fix that soon! 

Hurdle 2 to seems to be how many rows to enter ... 

```
> # need all unique columns to reshape ...
> table(doubleentrydf$paperid, doubleentrydf$who_entered)
                    
                     Ailene emw JHRL KP
  chen2000                1   0    1  0
  eckes-shephard2020      0   1    0  1
  finzi2020               1   0    1  0
  francon2020             0   1    0  1
  stridbeck2022           1   0    1  0
  vitasse2009             1   0    3  0
  zani2020                3   0    3  0
  zohnerpreprint          1   0    3  0
```

Hurdle 3 seems to be when to enter NA .... 

```
> comparedoubentry(dekavyalizziedfwide, c("KP", "emw"),  "authorsthink_evidence_gslxgrowth")
              paperid authorsthink_evidence_gslxgrowth.KP authorsthink_evidence_gslxgrowth.emw
1: eckes-shephard2020                       not mentioned                              notsure
2:        francon2020                       not mentioned                                 <NA>
3:        francon2020                                <NA>                                  yes

> comparedoubentry(deailenejannekedfwide, c("Ailene", "JHRL"),  "youthink_evidence_gslxgrowth")
         paperid youthink_evidence_gslxgrowth.Ailene youthink_evidence_gslxgrowth.JHRL
1:      chen2000                            not sure                              <NA>
2: stridbeck2022                                  no                              <NA>
3:     finzi2020                                <NA>                                no
4:     finzi2020                                 yes                              <NA>
5: stridbeck2022                                <NA>                                no
6:      chen2000                                <NA>                                no
```

**Comment by AileneKane** [comment]
@lizzieinvancouver I'm a bit confused about this example for Hurdle 3. It looks like none of us entered NA in this column (for example, I entered "not sure" for chen, no for stridbeck and yes for finzi, while Janneke entered no for all). Is the takeaway from this that we SHOULD have entered NA for some of these?.

**Comment by lizzieinvancouver** [comment]
@AileneKane Thanks for catching this. Agreed! This does not show it -- the NA here just means there was no agreement (I think; I did not have enough time for R coding this today), but I am pretty sure I did see NA were not expected (where notsure or notmentioned seemed appropriate).

**Comment by AileneKane** [comment]
@lizzieinvancouver Thanks for clarifying and thank you for all you are doing to keep us on track! I will go back and check my entries for this. How and when do you prefer to receive corrected entries? And should I send you my new entries separately from 1) my late submissions (still have one due to you last Friday) and 2) corrected, previously submitted entries?

**Comment by lizzieinvancouver** [comment]
@AileneKane Thank you for all your hard work (and my apologies for being a bit off yesterday)! I am sending an email later today with all this info and more; I'll also open a git issue as I think it would be great to discuss issues there as already you have helped me here. But in case you are reading now ... late submissions are less critically due!

**Comment by lizzieinvancouver** [comment]
Updates from yesterday's meeting:

- Entering >1 row -- definitely for different answers based on metrics, otherwise we will go either way: multiple rows okay (splitters of the world, unite!) or if you basically would enter the same for all columns beyond gsl_end_metric (in that case, you can put multiple entries in the growth or GSL metric columns and Lizzie will adjust in R). 
- If you have a paper that never seems to test for GSL x growth (and by this I mean *any* version of it — NOT just our version of it) for whatever reason (often this seems to happen in modeling papers) then you should enter data through gsl_end_metric  but then can enter NA for all following columns. Please FLAG these papers when you email your data to Lizzie. 
- I may have overstated the NA issue, I apologize but still -- be careful with NA!

New questions go in issue #7
